# Generated by Django 4.2.6 on 2023-11-16 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokiml', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='beranda',
            new_name='home',
        ),
    ]
